defaults:
  - dataset_base
  - _self_

connection_uri: "postgres://${oc.env:USER}:@localhost:5432/eicu"
save_dir: "${oc.env:PROJECT_DATA_DIR}/${cohort_name}"
subject_id_col: "uniquepid"
min_los: 3
min_admissions: 1
inputs:
  patients:
    query: |-
      SELECT uniquePID, gender, CASE WHEN ((age = '') IS NOT FALSE)  THEN NULL ELSE to_date((hospitaldischargeyear::BIGINT-REPLACE(age, '> 89','90')::BIGINT)::CHAR(4), 'YYYY') END AS year_of_birth
      FROM eicu_crd.patient
      WHERE uniquePID IN (
        SELECT uniquePID FROM eicu_crd.patient
        WHERE hospitaldischargeoffset > ${min_los}
        GROUP BY uniquePID
        HAVING COUNT(*) > ${min_admissions}
      )
    must_have: ["gender", "year_of_birth"]
  death:
    # query: "SELECT subject_id, deathtime FROM mimiciv_hosp.admissions WHERE deathtime IS NOT NULL"
    # need to join patient.csv with 
    query: "SELECT uniquePID AS uniquepid, hospitaladmitdatetime + interval '1 minute' * hospitaldischargeoffset AS deathtime FROM eicu_crd.patient WHERE hospitaldischargeoffset IS NOT NULL AND unitdischargelocation = 'Death'"
    ts_col: "deathtime"
  admissions:
    query: "SELECT uniquePID as uniquepid, hospitaladmitdatetime, hospitaladmitdatetime - interval '1 minute' * hospitaladmitoffset + interval '1 minute' * hospitaldischargeoffset as dischtime, hospitaladmitsource, wardid, hospitalid, ethnicity, admissionheight, admissionweight, hospitaldischargestatus, hospitaldischargelocation  FROM eicu_crd.patient"
    start_ts_col: "hospitaladmitdatetime"
    end_ts_col: "dischtime"
    start_columns:
      # - "admission_type"
      # - "admission_location"
      # - "language"
      # - "race"
      # - "marital_status"
      # - "insurance"
      - "hospitaladmitsource"
      - "wardid"
      - "hospitalid" #admission_location
      # - "language"
      - "ethnicity"
      - "admissionheight"
      - "admissionweight"
    end_columns:
      - "hospitaldischargelocation"
      - "hospitaldischargestatus"
    event_type: ["VISIT", "ADMISSION", "DISCHARGE"]
  icu_stays:
    query: "SELECT uniquePID as uniquepid, unittype, hospitaladmitdatetime - interval '1 minute' * hospitaladmitoffset as intime, hospitaladmitdatetime - interval '1 minute' * hospitaladmitoffset  + interval '1 minute' * unitdischargeoffset as outtime  FROM eicu_crd.patient where LOWER(unittype) LIKE '%icu%'"
    start_ts_col: "intime"
    end_ts_col: "outtime"
    start_columns: ["unittype"]
      #first_careunit: unittype
    end_columns: ["unittype"]
      # last_careunit: unittype
  diagnoses:
    query: |-
      SELECT
        patient.uniquePID as uniquepid,
        patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset + interval '1 minute' * patient.hospitaldischargeoffset as dischtime,
        ('ICD_9 '::TEXT || COALESCE((regexp_match(TRIM(diagnosis.icd9code), '[A-z]\d{1,3}\.\d+'))[1]::TEXT, NULL)) AS icd_code
      FROM (
        eicu_crd.diagnosis AS diagnosis JOIN eicu_crd.patient AS patient
        ON patient.patientunitstayid = diagnosis.patientunitstayid
      )
    ts_col: "dischtime"
  labs:
    query:
      - |-
        SELECT patient.uniquePID as uniquepid, 
          patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset + interval '1 minute' * lab.labresultoffset AS charttime,
          (lab.labname || ' (' || lab.labmeasurenamesystem || ')') AS lab_itemid,
          lab.labresult as labresult
        FROM (
          eicu_crd.lab AS lab JOIN eicu_crd.patient AS patient
          ON patient.patientunitstayid = lab.patientunitstayid
        )
    ts_col: "charttime"
  infusions:
    query: |-
      SELECT
        patient.uniquePID,
        infusiondrug.drugname AS infusion_itemid,
        infusiondrug.drugamount,
        infusiondrug.drugrate,
        infusiondrug.patientweight,
        patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset + interval '1 minute' * infusiondrug.infusionoffset AS starttime,
        CASE WHEN infusiondrug.drugname LIKE '%units/hr%' THEN patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * infusiondrug.infusionoffset + interval '60 minute' * (infusiondrug.drugamount::DECIMAL / infusiondrug.drugrate::FLOAT)
          WHEN ((infusiondrug.drugname LIKE '%mcg/kg/min%') AND ((infusiondrug.patientweight = '') IS NOT TRUE)) AND (infusiondrug.patientweight::FLOAT > 0) THEN patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * infusiondrug.infusionoffset + interval '1 minute' * (infusiondrug.drugamount::DECIMAL / COALESCE(infusiondrug.patientweight, '70')::FLOAT / infusiondrug.drugrate::FLOAT)
          ELSE patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * infusiondrug.infusionoffset + interval '1 minute' * (infusiondrug.drugamount::DECIMAL / infusiondrug.drugrate::FLOAT)
        END AS endtime
      FROM (
        eicu_crd.patient AS patient INNER JOIN eicu_crd.infusiondrug AS infusiondrug
        ON patient.patientunitstayid = infusiondrug.patientunitstayid
      ) WHERE ((infusiondrug.drugamount ~ '^\d+(\.\d+)?$') AND (infusiondrug.drugrate ~ '^\d+(\.\d+)?$')) AND (infusiondrug.drugrate::FLOAT > 0)
    start_ts_col: "starttime"
    end_ts_col: "endtime"
  procedures:
    query: |-
      SELECT
        patient.uniquePID as uniquepid,
        patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * treatment.treatmentoffset AS charttime,
        treatment.treatmentstring
      FROM (
        eicu_crd.patient AS patient INNER JOIN eicu_crd.treatment AS treatment
        ON treatment.patientunitstayid = patient.patientunitstayid
      )
    ts_col: "charttime"
  medications:
    query: |-
      SELECT
        patient.uniquePID as uniquepid,
        patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset + interval '1 minute' * medication.drugstartoffset AS starttime,
        patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset + interval '1 minute' * medication.drugstopoffset AS endtime,
        medication.drugname as medication
      FROM (
        eicu_crd.patient AS patient INNER JOIN eicu_crd.medication AS medication
        ON patient.patientunitstayid = medication.patientunitstayid
      )
      WHERE (patient.hospitaladmitdatetime - interval '1 minute'* hospitaladmitoffset) <= (patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * medication.drugstartoffset) AND (patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * medication.drugstopoffset) <= (patient.hospitaladmitdatetime - interval '1 minute'* hospitaladmitoffset + interval '1 minute' * patient.hospitaldischargeoffset) 
    start_ts_col: "starttime"
    end_ts_col: "endtime"
  cultures:
    query: |-
        SELECT patient.uniquePID as uniquepid, 
          patient.hospitaladmitdatetime - interval '1 minute' * patient.hospitaladmitoffset  + interval '1 minute' * microlab.culturetakenoffset AS charttime,
          ('culture' || ' (' || microlab.culturesite || ')') AS lab_itemid,
          microlab.organism::CHAR as organism
        FROM (
          eicu_crd.microlab AS microlab JOIN eicu_crd.patient AS patient
          ON patient.patientunitstayid = microlab.patientunitstayid
        )
    ts_col: "charttime"


measurements:
  static:
    single_label_classification:
      patients: ["gender"]
  functional_time_dependent:
    age:
      functor: AgeFunctor
      necessary_static_measurements: { "year_of_birth": "timestamp" }
      kwargs:
        dob_col: "year_of_birth"
    time_of_day:
      functor: TimeOfDayFunctor
  dynamic:
    multi_label_classification:
      admissions:
        - "hospitaladmitsource" #admission_type
        - "hospitalid" #admission_location
        - "wardid" #admission_location
        # - "language"
        - "ethnicity" # race
        # - "marital_status"
        # - "insurance"
        - "hospitaldischargestatus" # discharge location
        - hospitaldischargelocation
      icu_stays: ["unittype"]
      diagnoses: ["icd_code"]
      procedures: ["treatmentstring"]
      medications: ["medication"]
      cultures: ["organism"]
    multivariate_regression:
      labs: [["lab_itemid", "labresult"]]
      infusions: [["infusion_itemid", "drugamount"]]
    univariate_regression:
      admissions: ["admissionweight","admissionheight"]

outlier_detector_config:
  stddev_cutoff: 4.0
min_valid_vocab_element_observations: 25
min_valid_column_observations: 50
min_true_float_frequency: 0.1
min_unique_numerical_observations: 25
min_events_per_subject: 20
agg_by_time_scale: "2h"
DL_chunk_size: 4000


